version: "3"

services:
  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
      - "2345:2345"
    volumes:
      - ./backend:/app
  db:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql
      - mysql-logs:/var/log/mysql

volumes:
  mysql-volume:
  mysql-logs:
